### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by gdomingu**

### CODE REVIEW

**Review by Diamondbrandblue — APPROVED** [review]
h#llo

**Comment by 0938331819** [comment]
Hmode

**Comment by XAVIeraF1** [comment]
Hello what's up

**Review by nowakwp — COMMENTED** [review]
[bulk-sponsorships-template.csv](https://github.com/user-attachments/files/16174751/bulk-sponsorships-template.csv)

**Review by nowakwp — COMMENTED** [review]
#56

**Review by nowakwp — COMMENTED** [review]
[ @0938331819

**Comment by fonsecajuancarlos37-del** [comment]
> Hola

Hi

**Pull request closed without merging**
